server:
  port: 2024  
  servlet:
    context-path: /empgps_tracking

spring:
  datasource:
 #local database
#    url: jdbc:oracle:thin:@192.168.0.93:1521/orcl
#    username: DRUG_GIS_1
#    password: DRUG_GIS_1
   
 #live for local testing 
    url: jdbc:oracle:thin:@202.51.189.217:1521/gisdb
    username: drug_gis
    password: onTheRoad2trAck$
#   
#live database  
#    url: jdbc:oracle:thin:@192.168.8.233:1521:gisdb
#    username: drug_gis
#    password: onTheRoad2trAck$
    
    driver-class-name: oracle.jdbc.driver.OracleDriver
   # driver-class-name:  oracle.jdbc.OracleDriver
   

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true   

  application:
    name: empgps_tracking
  batch:
    job:
      enabled: false   
  
    
logging:
  level:
    io:
      app: TRACE
  file:
    path: ../empgps_tracking_Log
    name: ${logging.file.path}/empgps_tracking.log

 
